### ISSUE TITLE
Not working with 0.7.3 anymore

### ISSUE THREAD

**Issue by hardc0l2e** [saltcorn/carousel#2]
Tried to make it work with sample show views and image slider with captions but it doesn't work anymore, even the sample carousel on saltcorn.com site doesn't work anymore.

**Comment by glutamate** [comment]
Thanks for noticing, fixed with https://github.com/saltcorn/carousel/commit/02e246c9aa263c916e37bda39833875ae34ae389 / v 0.1.3
